import getTimezones from './getTimezones.mjs'
import fs from 'fs'

const data = await getTimezones()
const partsRegexp = /^(\w+)\/(.+)$/
const replacementList = {}
const functions = [`function join(...args) { return args.join('/') }`]
const zones = []

Object.entries(data).forEach(([name, coordinates]) => {
  const [, prefix, suffix] = name.split(partsRegexp)

  if (!replacementList[prefix]) {
    replacementList[prefix] = prefix

    functions.push(`function ${prefix}(suffix) { return join("${prefix}", suffix) }`)
  }

  zones.push(`[${prefix}("${suffix}")]: ${JSON.stringify(coordinates)},`)
})

fs.writeFileSync(
  'src/timezones.js',
  `
// generated by scripts/generate.mjs
module.exports = { ${zones.join('\n')} }
${functions.join('\n')}
`,
)
