// Turns Natural Earth's 110m land polygons into a single SVG path, committed
// as demo/src/map/land.ts. Same shape as generate.mjs: the heavy source file
// is downloaded by hand (see scripts/README.md), the generator runs locally,
// and only the small result is committed -- CI never regenerates anything.
import fs from 'fs'
import GeoJSONReader from 'jsts/org/locationtech/jts/io/GeoJSONReader.js'
import DouglasPeuckerSimplifier from 'jsts/org/locationtech/jts/simplify/DouglasPeuckerSimplifier.js'
import { VIEW, project } from '../demo/src/map/projection.ts'

const SOURCE = 'scripts/ne_110m_land.geojson'
const TARGET = 'demo/src/map/land.ts'

// Degrees. Coarse enough to halve the point count, fine enough that the
// coastline still reads as itself at a few hundred pixels wide.
const TOLERANCE = 0.4

// Square degrees. Drops specks that survive simplification but cannot be
// seen at map scale.
const MIN_AREA = 0.6

const reader = new GeoJSONReader()

const rings = geometry => {
  const out = []
  for (let i = 0; i < geometry.getNumGeometries(); i++) {
    const polygon = geometry.getGeometryN(i)
    if (polygon.getArea() < MIN_AREA) continue
    // Exterior ring only: at this scale interior holes (the Caspian, say)
    // are not worth the bytes.
    out.push(polygon.getExteriorRing().getCoordinates())
  }
  return out
}

// Relative commands with integer deltas: the same trick timeZones.ts uses,
// since short repetitive text compresses far better than absolute floats.
const toPath = ringList => {
  let path = ''
  for (const coordinates of ringList) {
    let previousX = 0
    let previousY = 0
    coordinates.forEach(({ x: lon, y: lat }, index) => {
      const [projectedX, projectedY] = project(lon, lat)
      const x = Math.round(projectedX)
      const y = Math.round(projectedY)
      if (index === 0) {
        path += `M${x} ${y}`
      } else {
        const dx = x - previousX
        const dy = y - previousY
        if (dx === 0 && dy === 0) return
        path += `l${dx} ${dy}`
      }
      previousX = x
      previousY = y
    })
    path += 'Z'
  }
  return path
}

const source = JSON.parse(fs.readFileSync(SOURCE, 'utf-8'))

const ringList = source.features.flatMap(feature => {
  const geometry = reader.read(JSON.stringify(feature.geometry))
  return rings(DouglasPeuckerSimplifier.simplify(geometry, TOLERANCE))
})

const path = toPath(ringList)

fs.writeFileSync(
  TARGET,
  `// Generated by scripts/generate-land.mjs from Natural Earth 110m land
// (public domain). Do not edit by hand -- run \`npm run generate:land\`.
//
// LAND_VIEW records the projection this path was built with; map/index.ts
// asserts it still matches VIEW, so changing the viewBox without
// regenerating fails loudly instead of quietly shifting the coastline out
// from under the timezone dots.
export const LAND_VIEW = ${JSON.stringify({ width: VIEW.width, height: VIEW.height, latMin: VIEW.latMin, latMax: VIEW.latMax })}

export const LAND_PATH =
  '${path}'
`,
  'utf-8',
)

const raw = fs.statSync(TARGET).size
console.log(`Generated ${TARGET}: ${ringList.length} rings, ${(raw / 1024).toFixed(1)} KB raw`)
