// Writes demo/src/map/zones.ts: the names of every timezone the library
// knows about, for the demo to plot.
//
// The demo cannot ask the library for this list (timeZones.ts is not part of
// the public API) and must not use Intl.supportedValuesOf() either: what
// that returns depends on the runtime's ICU version, so the map would show a
// slightly different world per browser. Reading the committed table instead
// keeps every visitor looking at the same map.
//
// Unlike the other generators this one needs no downloaded source, so it can
// be rerun any time: `npm run generate:zones`.
import fs from 'fs'

const SOURCE = 'src/timeZones.ts'
const TARGET = 'demo/src/map/zones.ts'

const source = fs.readFileSync(SOURCE, 'utf-8')
const table = JSON.parse(source.match(/JSON\.parse\('(.*)'\)/)[1])

const names = []
const walk = (region, path) => {
  for (const key of Object.keys(region)) {
    const value = region[key]
    const name = [...path, key]
    if (Array.isArray(value)) names.push(name.join('/'))
    else walk(value, name)
  }
}
walk(table, [])

// Etc/* is not a place: its single entry has no meaningful centre point, and
// Intl does not report it as a zone anyone lives in.
const plotted = names.filter(name => !name.startsWith('Etc/')).sort()

fs.writeFileSync(
  TARGET,
  `// Generated by scripts/generate-zones.mjs from src/timeZones.ts.
// Do not edit by hand -- run \`npm run generate:zones\`.
//
// Names only: coordinates always come from the daynight() result itself, so
// a dot's position and its colour can never come from different sources.
export const ZONES: readonly string[] = ${JSON.stringify(plotted, null, 2).replace(/"/g, "'")}
`,
  'utf-8',
)

console.log(`Generated ${TARGET}: ${plotted.length} zones`)
