/**
 * This script is used to calculate all tz center coordinates
 * It rely on data https://github.com/evansiroky/timezone-boundary-builder/
 *
 * Go to Releases https://github.com/evansiroky/timezone-boundary-builder/releases
 * Download a file timezones.geojson.zip
 * Paste its content (combined.json) into this folder (so require('./combined.json') works)
 * Run `node ./src/generateTz`
 */

const combined = require('./combined.json')

const jsts = require('jsts')
const fs = require('fs')
const geoJsonReader = new jsts.io.GeoJSONReader()

const result = {}

combined.features.forEach(feature => {
  const { tzid } = feature.properties
  const geometry = geoJsonReader.read(JSON.stringify(feature.geometry))
  const centroid = new jsts.algorithm.Centroid(geometry)
  const { x, y } = centroid.getCentroid()

  result[tzid] = [x, y]
})

const fileContent = `// generated by src/generateTZ.js

const coordinates: Record<string, [number, number]> = ${JSON.stringify(result, null, 2)}

export default coordinates
`

fs.writeFileSync('./src/timeZoneCoordinates.ts', fileContent)
